repos:
-   repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
    -   id: black
        args: [--line-length=79]
        language_version: python3

-   repo: https://www.github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
    -   id: flake8
        additional_dependencies: [flake8-docstrings]

-   repo: local
    hooks:
    - id: pytest
      name: pytest
      entry: pytest
      language: system
      pass_filenames: false
      types: [python]
      files: \.py$
      always_run: false
      stages: [pre-commit]